spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://dmldus-maria.cipsc2svfyax.ap-northeast-2.rds.amazonaws.com:3306/tabtab?serverTimezone=Asia/Seoul"
    username: admin
    password: admin-dmldus
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate